# Generated by Django 5.1.4 on 2024-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryaddress',
            name='zone',
            field=models.CharField(choices=[('1', 'Inside Dhaka'), ('2', 'Outside Dhaka'), ('3', 'Rajshahi'), ('4', 'Sylhet'), ('5', 'Chattogram'), ('6', 'Khulna'), ('7', 'Rangpur '), ('8', 'Barishal '), ('9', 'Mymensingh  ')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='deliveryzone',
            name='name',
            field=models.CharField(choices=[('inside_city', 'Dhaka'), ('outside_city', 'Outside City')], max_length=50, unique=True),
        ),
    ]
