# Generated by Django 5.1.4 on 2025-01-05 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliveryaddress_zone_alter_deliveryzone_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryoption',
            name='zone',
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='delivery_option',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='delivery.deliveryoption'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliveryoption',
            name='name',
            field=models.CharField(choices=[('standard', 'Standard Delivery'), ('express', 'Express Delivery'), ('pickup', 'Store Pickup')], default='standard', max_length=50),
        ),
        migrations.DeleteModel(
            name='DeliveryZone',
        ),
    ]
