# Generated by Django 5.1.4 on 2024-12-29 21:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='eligible_customers',
            field=models.ManyToManyField(blank=True, related_name='eligible_coupons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='minimum_spend',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
        ),
    ]
