# Generated by Django 5.1.4 on 2024-12-29 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0002_coupon_eligible_customers_coupon_minimum_spend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='valid_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateField(),
        ),
    ]
