# Generated by Django 5.1.4 on 2024-12-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounts', '0004_remove_coupon_eligible_customers'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='maximum_discount',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
