# Generated by Django 5.1.4 on 2024-12-30 12:35

import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter a valid phone number.', max_length=128, region='BD'),
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='123 Example Street', max_length=255, null=True)),
                ('area', models.CharField(blank=True, default='Dhaka Division', max_length=100, null=True)),
                ('state', models.CharField(blank=True, default='Dhaka', max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, default='1212', max_length=20, null=True)),
                ('country', models.CharField(blank=True, default='Bangladesh', max_length=100, null=True)),
                ('number', models.CharField(blank=True, default='+8801234567890', max_length=25, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
