# Generated by Django 5.1.4 on 2025-01-04 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_cart_shipping_fee'),
        ('discounts', '0006_alter_coupon_maximum_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discount_applied',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='total_price_after_discount',
        ),
        migrations.AddField(
            model_name='cart',
            name='ccoupon',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='discounts.coupon'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
