# Generated by Django 5.1.4 on 2025-01-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_cart_ccoupon_cart_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='shipping_fee',
        ),
    ]
