# Generated by Django 5.1.4 on 2025-02-11 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug_product_uuid'),
        ('seller_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='seller_accounts.seller'),
            preserve_default=False,
        ),
    ]
